baseURL = "https://sharonabishek.github.io/mynotes/"
languageCode = "en-us"
title = "Sharon Abishek"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]